### PR TITLE
Add dexHive under PublicDomains

### PR DESCRIPTION
**Pull request by odedniv**

### CODE REVIEW

**Comment by ppival** [comment]
Hi @odedniv, this doesn't appear to be a page with datasets, per se, am I missing something?

**Comment by odedniv** [comment]
Hey @ppival, is https://www.dexhive.com/library better?

**Comment by ppival** [comment]
Hmm, still doesn't really fit with the theme of all the other datasets, in that it's more a list than a dataset. What say you, @caesar0301 ?

**Comment by odedniv** [comment]
The link is to a list of community generated datasets

**Comment by caesar0301** [comment]
@odedniv I am sorry this is not a dataset source with downloadable assets for mining or analysis. More like a white page or index (bookmarks) indexing service.

**Pull request closed without merging**
