### PR TITLE
Fix no-description bug

### PR DESCRIPTION
**Pull request by savfod**
Hi! Two small commits

1. Looks like Travis updates are [broken](https://travis-ci.org/github/awesomedata/apd-core/jobs/744710995) because of [two](https://github.com/awesomedata/apd-core/blob/master/core/Museums/Metropolitan-Museum-of-Art-Collection-API.yml) [ds](https://github.com/awesomedata/apd-core/blob/master/core/Climate%2BWeather/German-Meteorological-Service-CDC.yml) without desription. Trying to fix that.
2. Slightly updating PyYAML version, as 3.12 is imcompatible with [UDEC](https://github.com/awesomedata/apd-core/blob/master/core/Energy/UDEC.yml) yaml

### CODE REVIEW

**Comment by ppival** [comment]
@caesar0301 does this look ok to you?

**Comment by savfod** [comment]
Hi!

Sorry for the reminder. But the project is cool, It would be great if the awesome-public-datasets page keeps updating again :)

Something like this pull-request may help. Or, alternatively, one may simply add an empty "description" field to [file1](https://github.com/awesomedata/apd-core/blob/master/core/Museums/Metropolitan-Museum-of-Art-Collection-API.yml), [file2](https://github.com/awesomedata/apd-core/blob/master/core/Climate%2BWeather/German-Meteorological-Service-CDC.yml) and [file3](https://github.com/awesomedata/apd-core/blob/master/core/Government/Berkeley-CA-Open-Data.yml).

**Comment by ppival** [comment]
Thanks for trying to help sort this out, @savfod. I've completed those three files, and we'll see what happens when I also accept this pull request.

**Comment by ppival** [comment]
Looks like that did the trick, thanks again! @savfod would you be so kind as to touch base with me at ppival@gmail.com?

**Pull request merged**
