### PR TITLE
Add Soil Moisture Dataset and GRSS DASE database

### PR DESCRIPTION
**Pull request by felixriese**
**1. Hyperspectral benchmark dataset on soil moisture**
homepage: https://doi.org/10.5281/zenodo.1227837

**2. IEEE Geoscience and Remote Sensing Society DASE Website**
homepage: http://dase.ticinumaerospace.com

### CODE REVIEW

**Comment by caesar0301** [comment]
@felixriese This data is awesome but it is already indexed by kaggle.com. I am struggling to control the volume of this repo to highlight some really HQ datasets outside some famous indexing engine like Kaggle. Thanks.

**Comment by caesar0301** [comment]
@felixriese I gave labels to make the contributor give more explanation about their data. Some people use this repo to advertise their commercial websites, while some about their publications papers. I want this to be a pure data-sharing list, in a limited one-page volume. I was not sure about the role of the second DASE while it is under maintenance. I will remove this label when you convince me about the data quality. Thanks.

**Comment by felixriese** [comment]
@caesar0301 Thank you for the very reasonable explanation. I updated the URL (http://dase.grss-ieee.org) of the database, which provides open access to datasets after registration. If this is not compliant with your rules, I will immediately remove this part of the pull request.

**Comment by caesar0301** [comment]
@felixriese Thanks. Bingo

**Comment by caesar0301** [comment]
This MR breaks the master pipeline. Could u please give another squashed merge request after my reverting?

**Comment by felixriese** [comment]
@caesar0301 Sorry about that. New merge request: https://github.com/awesomedata/apd-core/pull/85

**Pull request merged**
