### PR TITLE
add cv dataset collections

### PR DESCRIPTION
**Pull request by hofbi**
Added 2 CV dataset lists to Complementary collection

### CODE REVIEW

**Comment by ppival** [comment]
@hofbi I wonder if we should start a new category for Computer Vision, or might these fit under the existing MachineLearning or ImageProcessing categories?

Any thoughts?

**Comment by hofbi** [comment]
I added them here as they are not datasets itself, but collections of datasets. The upper lists are about single datasets right?

Generally I think image processing and computer vision are similar from a user perspective. I am more confused with the machine learning category itself. Usually the datasets in image processing are using for machine learning. So actually I would try to remove the ml category and move to the desired categories as all datasets can somehow be used for ml.

**Comment by hofbi** [comment]
I added them here as they are not datasets itself, but collections of datasets. The upper lists are about single datasets right?

Generally I think image processing and computer vision are similar from a user perspective. I am more confused with the machine learning category itself. Usually the datasets in image processing are using for machine learning. So actually I would try to remove the ml category and move to the desired categories as all datasets can somehow be used for ml.

**Comment by ppival** [comment]
Thanks @hofbi!

**Pull request merged**
