### PR TITLE
Add American-Ninja-Warrior-Obstacles.yml

### PR DESCRIPTION
**Pull request by kgarrett**

### CODE REVIEW

**Comment by ppival** [comment]
@kgarrett By george I *think* we've got it! Sometimes takes a while to actually show up on the site, so don't panic!

**Comment by kgarrett** [comment]
Woohoo! Thanks so much for your help @ppival!

**Comment by ppival** [comment]
@kgarrett Just remembered to check and see this file hasn't shown up - I think we put it in the main folder instead of under Sports somehow, so I'm exploring that and will fix it if I'm able :-/

**Comment by kgarrett** [comment]
@ppival, thanks for following up! I just wasn't sure how long 'takes a while' was xD

**Pull request merged**
