### PR TITLE
Add Inter-American Development Bank

### PR DESCRIPTION
**Pull request by branmora**
under social sciences

---
title: 38-Cloud
homepage: https://github.com/SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset
category: EarthScience
description: Contains 38 Landsat 8 scene images and their manually extracted pixel-level ground truths for cloud detection. They are cropped into multiple 384*384 patches. It has 8400 patches for training and 9201 patches for testing.
version: 1.0
keywords: Landsat 8, cloud detection, image segmentation, semantic segmentation.
image: https://github.com/SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset/blob/master/sample/blue_patch_192_10_by_12_LC08_L1TP_002053_20160520_20170324_01_T1.jpg
temporal:
spatial: 384*384
access_level: public
copyrights:
accrual_periodicity: 
specification:
data_quality: false
data_dictionary: 
language: en
license: Apache License
publisher:
  - name: 
    web: 
organization:
  - name: Laboratory for Robotic Vision (LRV), School of Engineering Science, Simon Fraser University, Canada
    web: 
issued_time: 2019.02
sources:
  - name: 
    access_url: 
references:
  - title: 
    reference:

### CODE REVIEW

**Comment by caesar0301** [comment]
@branmora As addressed in https://github.com/awesomedata/apd-core/blob/master/CONTRIBUTING.md, we are expecting datasets "Able to be downloaded directly from the linked site, i.e., not barred by login or purchasing". Could you please update the data link?

**Comment by yeemey** [comment]
It looks like the IADB datasets can be accessed without login or purchasing through the actual homepage link provided in the yml. The 38-cloud PR description above is an error. I found that this same PR description automatically populates when I opened a PR too.

**Comment by tfmorris** [comment]
It looks to me like there are two links:
1. Kaggle (which requires a login)
2. Simon Fraser University (which doesn't) - https://vault.sfu.ca/index.php/s/pymNqYF09JkM8Bp/download (redirected through short url https://goo.gl/683SHf)

The latter could be added as the access URL for the data set

**Comment by branmora** [comment]
@yeemey is correct. The 38 PR description was auto populated and is not correct. Please take a look at the actual commit. You will find the correct URL to the Open Data Portal there.

`---
title: Inter-American Development Bank Open Data
homepage: https://data.iadb.org/
category: SocialSciences `

**Comment by tfmorris** [comment]
@branmora You should be able to edit the PR description. That might make it less confusing.

**Comment by ppival** [comment]
Sorry for the confusion - should be added now

**Pull request merged**
