### PR TITLE
Adding ANW data

### PR DESCRIPTION
**Pull request by kgarrett**
---
title: 38-Cloud
homepage: https://github.com/SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset
category: EarthScience
description: Contains 38 Landsat 8 scene images and their manually extracted pixel-level ground truths for cloud detection. They are cropped into multiple 384*384 patches. It has 8400 patches for training and 9201 patches for testing.
version: 1.0
keywords: Landsat 8, cloud detection, image segmentation, semantic segmentation.
image: https://github.com/SorourMo/38-Cloud-A-Cloud-Segmentation-Dataset/blob/master/sample/blue_patch_192_10_by_12_LC08_L1TP_002053_20160520_20170324_01_T1.jpg
temporal:
spatial: 384*384
access_level: public
copyrights:
accrual_periodicity: 
specification:
data_quality: false
data_dictionary: 
language: en
license: Apache License
publisher:
  - name: 
    web: 
organization:
  - name: Laboratory for Robotic Vision (LRV), School of Engineering Science, Simon Fraser University, Canada
    web: 
issued_time: 2019.02
sources:
  - name: 
    access_url: 
references:
  - title: 
    reference:

### CODE REVIEW

**Comment by ppival** [comment]
Duplicate of #108 added yesterday, but thanks!

**Comment by kgarrett** [comment]
Hi @ppival! I'm not very good at github, so I apologize. I was trying to add a dataset to the Sport category. I really doubt it is a duplicate. 
screen shot 2019-02-15 at 2 20 50 pm
I think this was what I was trying to merge.

**Comment by ppival** [comment]
@kgarrett Ahh, I see. From the bottom of the screen where you took that screen shot is there a green button to Create Pull Request? You may have to be in the edit mode (pencil icon in upper right) for it to show...

**Comment by kgarrett** [comment]
@ppival I'm not seeing that. My view: 
screen shot 2019-02-15 at 2 38 44 pm
(I'm in edit mode on the screen where I took the last screenshot)

**Comment by ppival** [comment]
@kgarrett try checking the button to create a new branch, then look for the Create Pull Request...

**Comment by kgarrett** [comment]
@ppival No luck. 
screen shot 2019-02-15 at 2 47 42 pm
Thanks for your help. Seriously. I feel like an idiot.

**Comment by ppival** [comment]
@kgarrett Trust me, you're not :-) I just click around and hope I don't break something myself :-) So can you hit the Propose File change button, and what happens then?

**Comment by kgarrett** [comment]
@ppival No, it's grayed out. I'm not able to click the Propose file change button.

**Comment by ppival** [comment]
@kgarrett OK, I'm at https://github.com/kgarrett/apd-core/blob/master/core/Sports/American-Ninja-Warrior-Obstacles.txt and notice a couple of things. First, to integrate with this collection the filename has to end in .yml - when you click the edit pencil you should have the ability to change the name - scroll to the right and just replace .txt with .yml

Second, I notice a typo in the URL of the resource - there's an extra "h" in there...

Then hit whatever green button appears at the bottom and let's see where that goes...

**Comment by kgarrett** [comment]
@ppival Cool. Yeah, I think that worked!

**Comment by ppival** [comment]
@kgarrett Hmm, still missing something - I didn't get anything at this end as a new pull request. What's supposed to be happening is that from your version of the repository you're supposed to be able to indicate that you have a file you'd like to merge into the project. We get a notice of that, check it, and if all looks good, approve it. But no notice yet at this end... Do you see something like this at your end?

image

**Comment by kgarrett** [comment]
I think I really got it this time!
https://github.com/awesomedata/apd-core/pull/110

**Pull request closed without merging**
